package app

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func sidecarOpts(dir string) SidecarOptions {
	return SidecarOptions{
		Upstream:   "warehouse",
		Deployment: "concierge",
		Namespace:  "acme",
		Out:        filepath.Join(dir, "warehouse-auth-sidecar.yaml"),
	}
}

// Two artifacts, applied by different people to different things: kmx
// applies the ConfigMap into a namespace it was named, and never touches
// somebody else's Deployment.
func TestTheSidecarAppliesItsConfigAndNotYourDeployment(t *testing.T) {
	f := newAddFixture(t, warehouseService, "notfound", nil)
	t.Setenv("KMX_TEST_STDIN", filepath.Join(f.dir, "stdin"))
	t.Setenv("KMX_TEST_SEAM_TLS", seamTLSSecret(t))

	opt := sidecarOpts(f.dir)
	if err := f.app.ToolsSidecar(opt); err != nil {
		t.Fatal(err)
	}
	patchPath := strings.TrimSuffix(opt.Out, ".yaml") + ".patch.yaml"
	if _, err := os.Stat(patchPath); err != nil {
		t.Fatalf("the Deployment patch was not written: %v", err)
	}
	args := readFile(t, f.argsLog)
	if !strings.Contains(args, "apply -f "+opt.Out) {
		t.Fatalf("the shim's config was not applied:\n%s", args)
	}
	if strings.Contains(args, "patch deployment") || strings.Contains(args, patchPath) {
		t.Fatalf("kmx patched a workload it does not own:\n%s", args)
	}
	// The shim verifies the seam, so the authority has to be where it runs.
	written := readFile(t, filepath.Join(f.dir, "stdin"))
	if !strings.Contains(written, "kaimahi-plane-ca") {
		t.Fatalf("the authority was not published into the runtime's namespace:\n%s", written)
	}
	notes := f.errOut.String()
	if !strings.Contains(notes, "patch deployment concierge") {
		t.Fatalf("the operator is not given the command for their half:\n%s", notes)
	}
	if !strings.Contains(notes, "127.0.0.1:8099/mcp/") {
		t.Fatalf("the operator is not told what to point the client at:\n%s", notes)
	}
}

// --no-apply writes and stops, the same contract `kmx tools add` has.
func TestTheSidecarNoApplyMutatesNothing(t *testing.T) {
	f := newAddFixture(t, warehouseService, "notfound", nil)
	opt := sidecarOpts(f.dir)
	opt.NoApply = true
	if err := f.app.ToolsSidecar(opt); err != nil {
		t.Fatal(err)
	}
	args := readFile(t, f.argsLog)
	for _, forbidden := range []string{"apply", "patch", "create"} {
		if strings.Contains(args, forbidden) {
			t.Fatalf("--no-apply ran %q:\n%s", forbidden, args)
		}
	}
}

// No flag, and no generated byte, carries credential material.
func TestTheSidecarNamesTheSecretAndNeverValuesIt(t *testing.T) {
	f := newAddFixture(t, warehouseService, "notfound", nil)
	opt := sidecarOpts(f.dir)
	opt.Out = "-"
	if err := f.app.ToolsSidecar(opt); err != nil {
		t.Fatal(err)
	}
	printed := f.out.String()
	if !strings.Contains(printed, "name: kaimahi-warehouse-token") ||
		!strings.Contains(printed, "key: api-key") {
		t.Fatalf("the shim does not reference the Secret by name:\n%s", printed)
	}
	if strings.Contains(printed, "kmh_") {
		t.Fatalf("a token shape reached the generated documents:\n%s", printed)
	}
}
